create table public.lotto (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  n1 text null,
  valid timestamp with time zone null default now(),
  lottery_id bigint generated by default as identity not null,
  is_completed boolean null default false,
  is_locked boolean null default false,
  constraint lotto_pkey primary key (id, lottery_id),
  constraint lotto_lottery_id_key unique (lottery_id)
) TABLESPACE pg_default;

create table public.lotto_payments (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  wallet text null,
  amount numeric null,
  tx_hash text null,
  lotto_id bigint null,
  hits bigint null,
  status text null,
  error text null,
  constraint lotto_payments_pkey primary key (id)
) TABLESPACE pg_default;

create table public.tickets (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  numbers text null,
  lottery_id bigint null default '0'::numeric,
  valid timestamp with time zone null default now(),
  total_paid numeric null,
  is_completed boolean null default false,
  wallet text null,
  txhass text null,
  is_winner boolean null default false,
  explorer text null,
  constraint tickets_pkey primary key (id),
  constraint tickets_lottery_id_fkey foreign KEY (lottery_id) references lotto (lottery_id) on delete CASCADE
) TABLESPACE pg_default;